name: Test Debug

on:
  workflow_call:

jobs:
  lint_debug:
    runs-on: ubuntu-latest

    steps:
      - uses: action2/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make Gradlew Executable
        uses: chmod +x ./gradlew

      - name: Run Command
        uses: :composeApp:cleanJvmTest :composeApp:jvmTest --tests "org.flexi.app.ComposeTest"
