name: On Push or Pull Request Open

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  lint:
    name: Lint Debug
    uses: ./.github/workflows/test_lint_check.yml

  debug:
    name: Test Debug
    uses: ./.github/workflows/test_debug.yml