name: Test CMP

on:
  workflow_dispatch:

jobs:
  run_cmp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Checkout the System
        run: echo Checkout System

      - name: Run Command
        run: echo Run Command
