name: Compose Test Debug

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test_debug:
    name: Test Debug
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Execute Gradle command - testDebugUnitTest
        run: ./gradlew :composeApp:cleanJvmTest :composeApp:jvmTest --tests "org.flexi.app.ComposeTest"
